[package]
name = "library"
version = "0.1.0"
authors = ["PACKAGE AUTHOR <package_author@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# デフォルトで有効になるフィーチャ
default = ["parallel", "serde"]

# 依存クレートを持たないフィーチャ
special = []

# 依存クレートを持つフィーチャ
parallel = ["crossbeam"]

# 依存クレートのフィーチャを有効にするフィーチャ
nightly = ["crossbeam/nightly"]

# いろいろな依存関係を混ぜた例
full = ["crossbeam/nightly", "parallel", "serde"]

[dependencies]
crossbeam = {version = "0.7.3", optional = true}
serde = {version = "1.0.111", optional = true}
